---
title: Тема оформления Hyprland (часть 2)
summary: FIXME Первая статья из серии статей про конфигурацию Hyprland. В ней я расскажу как настроил тему оформления, а именно внешний вид окон и виджетов, курсор и иконки.
categories:
  - Настройка окружения Hyprland от начала до конца
tags:
  - linux
  - hyprland
date: 2025-07-17T22:46:00
draft: true
---

Эта статья является продолжением [[denote:20250613T185635][первой]] про настройку окружения Hyprland. В текущей статье рассмотрю более детально настройку внешнего вида конкретных элементов окружения, а также некоторые полезные утилиты, которые я использую в своей конфигурации.

* Иконки
Мой выбор пал на популярную тему иконок [[https://github.com/vinceliuice/Qogir-icon-theme][Qogir]], потому что мне нравятся плоские иконки. Для установки темы из AUR выполнил команду:
#+begin_src sh
yay -S qogir-icon-theme
#+end_src

В EndeavourOS, который я использую, иконки Qogir уже предустановлены в пакете =eos-qogir-icons=.

* Настройка Status bar
В Hyprland есть несколько вариантов статус-баров, в [[https://wiki.hyprland.org/Useful-Utilities/Status-Bars/][официальной вики]] перечислены некоторые из них. Самым популярным является [[https://github.com/Alexays/Waybar][Waybar]], на нём я и остановился. Он поддерживает множество модулей, которые можно настраивать в файле конфигурации. Мой конфиг можно найти [[https://github.com/ismd/dotfiles/tree/master/conf/config/waybar][здесь]]. На момент написания статьи из кастомных модулей в конфиге я использовал =custom/weather=, для которого необходима установленная утилита =wttrbar=. Остальные модули являются стандартными.

Установка и запуск стандартные: =yay -S waybar= и добавление =exec-once = waybar= в =hyprland.conf=.

* Система уведомлений
Для отображения системных уведомлений понадобится демон уведомлений. В мире Linux самым популярным является [[https://github.com/dunst-project/dunst][dunst]]. Он лёгкий, настраиваемый и поддерживает множество функций. Этот проект изначально был создан для X11, но теперь поддерживает и Wayland. Несмотря на поддержку Wayland, я решил использовать утилиту [[https://github.com/emersion/mako][mako]], которая является нативной для Wayland.

Установка и запуск стандартные: =yay -S mako= и добавление =exec-once = mako= в =hyprland.conf=. Несмотря на то, что рекомендуется не запускать явно демон уведомлений (ни =mako=, ни =dunst=), я предпочитаю запускать его явно, чтобы не было конфликтов, если установлены оба демона.

Вместе с демоном =mako= устанавливается утилита =makoctl=, с помощью которой можно управлять уведомлениями. Например, полезная команда для вывода истории уведомлений:
#+begin_src sh
makoctl history
#+end_src

* Блокировщик экрана
* Яркость экрана
* Управление сетью
* Управление bluetooth
* Idle management =TODO=
* Скриншоты
* Управление питанием =TODO=
